[versions]
agp_version = "7.3.0"
lifecycle_version = "2.5.1"

[libraries]

appcompat = "androidx.appcompat:appcompat:1.5.1"
cardview = "androidx.cardview:cardview:1.0.0"
webkit = "androidx.webkit:webkit:1.5.0"
recyclerview = "androidx.recyclerview:recyclerview:1.2.1"
preference = "androidx.preference:preference:1.2.0"
annotation = "androidx.annotation:annotation:1.5.0"
browser = "androidx.browser:browser:1.4.0"
biometric = "androidx.biometric:biometric:1.1.0"
palette = "androidx.palette:palette:1.0.0"
core-kts = "androidx.core:core-ktx:1.9.0"
constraintlayout = "androidx.constraintlayout:constraintlayout:2.1.4"
multidex = "androidx.multidex:multidex:2.0.1"
work = "androidx.work:work-runtime-ktx:2.6.0"

lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "lifecycle_version" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle_version" }
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle_version" }


[bundles]
androidx = ["appcompat", "cardview", "webkit", "recyclerview", "preference", "annotation", "browser", "biometric", "palette", "core-kts", "constraintlayout", "multidex", "lifecycle-process", "lifecycle-runtime-ktx", "lifecycle-viewmodel-ktx", "work"]


[plugins]
application = { id = "com.android.application", version.ref = "agp_version" }
library = { id = "com.android.library", version.ref = "agp_version" }
