[versions]
accompanist_version = "0.26.1-alpha"
compose_version = "1.3.0-beta03"
compose_material3_version = "1.0.0-beta03"
compose_compiler_version = "1.3.0"

[libraries]

accompanist-swiperefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "accompanist_version" }
accompanist-flowlayout = { module = "com.google.accompanist:accompanist-flowlayout", version.ref = "accompanist_version" }
accompanist-drawablepainter = { module = "com.google.accompanist:accompanist-drawablepainter", version.ref = "accompanist_version" }
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist_version" }
accompainist-webview = { module = "com.google.accompanist:accompanist-webview", version.ref = "accompanist_version" }

material3-core = { module = "androidx.compose.material3:material3", version.ref = "compose_material3_version" }
material3-windowsize = { module = "androidx.compose.material3:material3-window-size-class", version.ref = "compose_material3_version" }

material3-adapter = "com.google.android.material:compose-theme-adapter-3:1.0.19"

activity = "androidx.activity:activity-compose:1.6.0"
animations = { module = "androidx.compose.animation:animation-graphics", version.ref = "compose_version" }
ui = { module = "androidx.compose.ui:ui", version.ref = "compose_version" }
runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "compose_version" }
ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose_version" }
foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose_version" }
material = { module = "androidx.compose.material:material", version.ref = "compose_version" }
material-icons-core = { module = "androidx.compose.material:material-icons-core", version.ref = "compose_version" }
material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose_version" }

charty = "com.himanshoe:charty:1.1.3-alpha05"

gap = "jp.wasabeef:gap:1.1.0"

number-picker = "com.chargemap.compose:numberpicker:1.0.3"

date-fieled = "com.github.LanarsInc:compose-date-text-field:1.0.2"
markdown = "com.mikepenz:multiplatform-markdown-renderer-android:0.6.1"


[bundles]
accompanist = ["accompanist-swiperefresh", "accompanist-flowlayout", "accompanist-drawablepainter", "accompanist-systemuicontroller", "accompainist-webview"]
compose = ["activity", "animations", "material3-core", "material3-windowsize", "material3-adapter", "ui", "ui-tooling", "runtime-livedata", "foundation", "material", "material-icons-core", "material-icons-extended", "date-fieled", "markdown", ]
charting = ["charty"]
