[versions]
accompanist_version = "0.34.0"
compose_version = "1.6.8"
compose_material3_version = "1.2.1"
compose_compiler_version = "1.5.11"
markdown_version = "0.22.0"

[libraries]

accompanist-drawablepainter = { module = "com.google.accompanist:accompanist-drawablepainter", version.ref = "accompanist_version" }
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist_version" }
accompanist-themeadapter = { module = "com.google.accompanist:accompanist-themeadapter-material3", version.ref = "accompanist_version" }

material3-core = { module = "androidx.compose.material3:material3", version.ref = "compose_material3_version" }
material3-windowsize = { module = "androidx.compose.material3:material3-window-size-class", version.ref = "compose_material3_version" }

activity = "androidx.activity:activity-compose:1.9.0"
animations = { module = "androidx.compose.animation:animation-graphics", version.ref = "compose_version" }

lifecycle = "androidx.lifecycle:lifecycle-runtime-compose:2.8.2"
ui = { module = "androidx.compose.ui:ui", version.ref = "compose_version" }
ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose_version" }
foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose_version" }
material = { module = "androidx.compose.material:material", version = "1.6.8" }
material-icons-core = { module = "androidx.compose.material:material-icons-core", version.ref = "compose_version" }
material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose_version" }

compose-webview = "io.github.kevinnzou:compose-webview:0.33.6"

material-motion = "io.github.fornewid:material-motion-compose-core:1.1.2"

charty = "com.himanshoe:charty:1.1.3-alpha05"

gap = "jp.wasabeef:gap:1.1.0"

number-picker = "com.chargemap.compose:numberpicker:1.0.3"

date-field = "com.github.nonproto:compose-date-text-field:73c012b665"
markdown = { module = "com.mikepenz:multiplatform-markdown-renderer", version.ref = "markdown_version" }
markdown-m3 = { module = "com.mikepenz:multiplatform-markdown-renderer-m3", version.ref = "markdown_version" }
markdown-coil = { module = "com.mikepenz:multiplatform-markdown-renderer-coil2", version.ref = "markdown_version" }

[bundles]
accompanist = ["accompanist-drawablepainter", "accompanist-systemuicontroller", "accompanist-themeadapter"]
compose = ["activity", "compose-webview", "animations", "material3-core", "material3-windowsize", "lifecycle", "ui", "ui-tooling", "foundation", "material", "material-icons-core", "material-icons-extended", "date-field", "markdown", "markdown-m3", "markdown-coil", "material-motion"]
charting = ["charty"]
