[versions]
aboutlibVersion = "12.2.4"
cascadeComposeVersion = "2.3.0"
cascadeVersion = "2.3.0"
coilVersion = "3.3.0"
fastAdapterVersion = "5.7.0"
firebaseBomVersion = "34.2.0"
firebasePluginVersion = "3.0.6"
googleServicesPluginVersion = "4.4.3"
iconicsVersion = "5.4.0"
injektCoreVersion = "1.16.1"
kotlinResultVersion = "2.1.0"
ktfmtVersion = "0.23.0"
okhttpVersion = "5.1.0"
photoViewVersion = "2.3.0"
retrofitVersion = "3.0.0"
rxbindingVersion = "1.0.1"
sandwichVersion = "2.1.2"
simpleIconsVersion = "1.0.0"
sqliteAndroidVersion = "3.49.0"
sqliteVersion = "2.5.2"
taptargetviewVersion = "1.15.0"
viewTooltipVersion = "f79a8955ef"


[libraries]
cascade-compose = { module = "me.saket.cascade:cascade-compose", version.ref = "cascadeComposeVersion" }
cascade = { module = "me.saket.cascade:cascade", version.ref = "cascadeVersion" }
injekt-core = { module = "uy.kohesive.injekt:injekt-core", version.ref = "injektCoreVersion" }
material = "com.google.android.material:material:1.13.0"
desugaring = "com.android.tools:desugar_jdk_libs:2.1.5"
photoView = { module = "com.github.chrisbanes:PhotoView", version.ref = "photoViewVersion" }
play-services = "com.google.android.gms:play-services-gcm:17.0.0"
flex-box = "com.google.android.flexbox:flexbox:3.0.0"
#needed for token bucket to work
guava-fix = "com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava"


coil3 = { module = "io.coil-kt.coil3:coil", version.ref = "coilVersion" }
coil3-svg = { module = "io.coil-kt.coil3:coil-svg", version.ref = "coilVersion" }
coil3-gif = { module = "io.coil-kt.coil3:coil-gif", version.ref = "coilVersion" }
coil3-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coilVersion" }

coil3-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coilVersion" }

disklrue = "com.jakewharton:disklrucache:2.0.2"

firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBomVersion" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }

iconics-core = { module = "com.mikepenz:iconics-core", version.ref = "iconicsVersion" }
iconics-views = { module = "com.mikepenz:iconics-views", version.ref = "iconicsVersion" }
iconics-compose = { module = "com.mikepenz:iconics-compose", version.ref = "iconicsVersion" }


jsoup = "org.jsoup:jsoup:1.21.2"

kotlin-result = { module = "com.michael-bull.kotlin-result:kotlin-result", version.ref = "kotlinResultVersion" }
kotlin-result-coroutines = { module = "com.michael-bull.kotlin-result:kotlin-result-coroutines", version.ref = "kotlinResultVersion" }

rx-android = "io.reactivex:rxandroid:1.2.1"
rx-java = "io.reactivex:rxjava:1.3.8"
rx-relay = "com.jakewharton.rxrelay:rxrelay:1.2.0"
rxbinding-kotlin = { module = "com.jakewharton.rxbinding:rxbinding-kotlin", version.ref = "rxbindingVersion" }
rxbinding-appcompat-v7 = { module = "com.jakewharton.rxbinding:rxbinding-appcompat-v7-kotlin", version.ref = "rxbindingVersion" }
rxbinding-appcompat-v4 = { module = "com.jakewharton.rxbinding:rxbinding-support-v4-kotlin", version.ref = "rxbindingVersion" }
rxbinding-recycler-v7 = { module = "com.jakewharton.rxbinding:rxbinding-recyclerview-v7-kotlin", version.ref = "rxbindingVersion" }

j2k-subsample = "com.github.jays2kings:subsampling-scale-image-view:756849e"

simple-icons = { module = "br.com.devsrsouza.compose.icons.android:simple-icons", version.ref = "simpleIconsVersion" }
sqlite-android = { module = "com.github.requery:sqlite-android", version.ref = "sqliteAndroidVersion" }
storio-sqlite = "com.github.inorichi.storio:storio-sqlite:8be19de"
storio-common = "com.github.inorichi.storio:storio-common:8be19de"
sqlite = { module = "androidx.sqlite:sqlite", version.ref = "sqliteVersion" }
tachi-image-decoder = "com.github.tachiyomiorg:image-decoder:7879b45"
tachi-source-api = "org.tachiyomi:source-api:1.1"
tachi-directional-view-pager = "com.github.tachiyomiorg:DirectionalViewPager:1.0.0"
tachi-unifile = "com.github.tachiyomiorg:unifile:a9de196cc7"


# TLS 1.3 support for Android < 10
conscrypt = "org.conscrypt:conscrypt-android:2.5.3"
conductor = "com.bluelinelabs:conductor:3.2.0"
conductor-supportpref = "com.github.tachiyomiorg:conductor-support-preference:3.1.8"

fast-adapter = { module = "com.mikepenz:fastadapter", version.ref = "fastAdapterVersion" }
fast-adapter-binding = { module = "com.mikepenz:fastadapter-extensions-binding", version.ref = "fastAdapterVersion" }

flexible-adapter-core = "com.github.arkon.FlexibleAdapter:flexible-adapter:c8013533"
flexible-adapter-ui = "com.github.arkon.FlexibleAdapter:flexible-adapter-ui:c8013533"

okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttpVersion" }
okhttp-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttpVersion" }
okhttp-dnsoverhttps = { module = "com.squareup.okhttp3:okhttp-dnsoverhttps", version.ref = "okhttpVersion" }
okio = "com.squareup.okio:okio:3.16.0"

sandwich = { module = "com.github.skydoves:sandwich", version.ref = "sandwichVersion" }
sandwich-retrofit = { module = "com.github.skydoves:sandwich-retrofit", version.ref = "sandwichVersion" }
sandwich-retrofit-serialization = { module = "com.github.skydoves:sandwich-retrofit-serialization", version.ref = "sandwichVersion" }

taptargetview = { module = "com.getkeepsafe.taptargetview:taptargetview", version.ref = "taptargetviewVersion" }
versioncompare = "io.github.g00fy2:versioncompare:1.5.0"

timber = "com.jakewharton.timber:timber:5.0.1"

aboutLibraries-compose = { module = "com.mikepenz:aboutlibraries-compose-m3", version.ref = "aboutlibVersion" }

leakcanary = "com.squareup.leakcanary:leakcanary-android:2.14"
pastelplaceholders = "com.github.zedlabs:pastelPlaceholders:1.0.4"
fuzzysearch = "me.xdrop:fuzzywuzzy:1.4.0"
tokenbucket = "org.isomorphism:token-bucket:1.7"

retrofit-core = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofitVersion" }
retrofit-serialization = { module = "com.squareup.retrofit2:converter-kotlinx-serialization", version.ref = "retrofitVersion" }
retrofit-scalars = { module = "com.squareup.retrofit2:converter-scalars", version.ref = "retrofitVersion" }


#test libs
junit = "junit:junit:4.13.2"
mockk = "io.mockk:mockk:1.14.5"
kotest-assertions = "io.kotest:kotest-assertions-core-jvm:6.0.2"
viewTooltip = { module = "com.github.nonproto:ViewTooltip", version.ref = "viewTooltipVersion" }

[plugins]
about-libraries = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "aboutlibVersion" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServicesPluginVersion" }
firebase = { id = "com.google.firebase.crashlytics", version.ref = "firebasePluginVersion" }
ktfmt = { id = "com.ncorti.ktfmt.gradle", version.ref = "ktfmtVersion" }

[bundles]
coil = [ "coil3", "coil3-compose", "coil3-svg", "coil3-gif", "coil3-okhttp" ]
conductor = ["conductor", "conductor-supportpref"]
fastadapter = ["fast-adapter", "fast-adapter-binding"]
firebase = ["firebase-analytics", "firebase-crashlytics"]
flexibleadapter = ["flexible-adapter-core", "flexible-adapter-ui"]
google = ["material", "guava-fix", "play-services", "flex-box"]
iconics = ["iconics-core", "iconics-views", "iconics-compose"]
ok = ["okhttp", "okhttp-logging-interceptor", "okhttp-dnsoverhttps", "okio"]
sandwich = ["sandwich", "sandwich-retrofit", "sandwich-retrofit-serialization"]
tachiyomi = ["tachi-image-decoder", "tachi-source-api", "tachi-directional-view-pager", "tachi-unifile"]
tests = ["junit", "mockk", "kotest-assertions"]
retrofit = ["retrofit-core", "retrofit-serialization", "retrofit-scalars"]
results = ["kotlin-result", "kotlin-result-coroutines"]
rx = ["rx-android", "rx-java", "rx-relay", "rxbinding-kotlin", "rxbinding-appcompat-v7", "rxbinding-appcompat-v4", "rxbinding-recycler-v7"]
