name: Scan with Detekt

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '25 8 * * 5' # Run at 8:25 AM UTC on Fridays.
  workflow_dispatch:

jobs:
  scan:
    name: Scan
    runs-on: ubuntu-latest

    # Required permissions for the CodeQL Action to upload SARIF results.
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Detekt Analysis
        uses: detekt/detekt-action@v1
        with:
          # Path to the config file (optional).
          # config: ${{ github.workspace }}/config/detekt/detekt.yml

          # Automatically generates a SARIF report for Code Scanning.
          report_path: ${{ github.workspace }}/detekt.sarif

      - name: Upload SARIF report to GitHub
        uses: github/codeql-action/upload-sarif@v3
        # Ensures the report is uploaded even if Detekt finds issues and fails the job.
        if: success() || failure()
        with:
          sarif_file: ${{ github.workspace }}/detekt.sarif
