name: Release app
on:
  push:
    tags:
      - '*'
jobs:
  check_wrapper:
    name: Validate Gradle Wrapper
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1.0.4

  build:
    name: Build app
    needs: check_wrapper
    runs-on: ubuntu-latest

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ github.token }}

      - name: Clone repo
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Copy ci gradle.properties
        run: |
          mkdir -p ~/.gradle
          cp .github/runner-files/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Write google-services.json
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: app/google-services.json
          contents: ${{ secrets.GOOGLE_SERVICE_JSON }}
          write-mode: overwrite # optional, default is preserve

      - name: Build app
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: assembleStandardRelease
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true

      - name: Sign APK
        uses: r0adkll/sign-android-release@v1.0.4
        with:
          releaseDirectory: app/build/outputs/apk/standard/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Prep build artifacts for release
        run: |
          echo "VERSION_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
          cp ${{ env.SIGNED_RELEASE_FILE }} neko.apk
          md5=`md5sum neko.apk | awk '{ print $1 }'`
          echo " #### MD5: $md5" >> CurrentChangeLog.MD

      - name: Create Release
        uses: ncipollo/release-action@v1.8.6
        with:
          allowUpdates: true
          bodyFile: "CurrentChangeLog.MD"
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          replacesArtifacts: true
          artifacts: "neko.apk"
